name: Check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # for checkout
  actions: read # for actions-timeline

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: actions-timeline
        # cspell:ignore kesin
        uses: Kesin11/actions-timeline@6905b677e042d41193107842cc5c7b715bef0042 # v2.0.3

      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@9b21598af8d4dfc302e5a30250007de0fda92acc # v1.1.1

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: "commitlint (push: initial commit)"
        id: commitlint-push-initial
        # commit hash will be 0000000000000000000000000000000000000000 if it doesn't exist
        if: github.event_name == 'push' && github.event.before == '0000000000000000000000000000000000000000'
        run: bun commitlint --verbose --to ${{github.event.after}}

      - name: commitlint (push)
        if: github.event_name == 'push' && steps.commitlint-push-initial.outcome == 'skipped'
        run: bun commitlint --verbose --from ${{github.event.before}} --to ${{github.event.after}}

      - name: commitlint (pull_request)
        if: github.event_name == 'pull_request'
        run: |
          bun commitlint --verbose --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}

      - name: Biome
        run: bun biome ci --error-on-warnings .

      - name: cspell
        run: bun cspell "**/*"

      - name: tsc
        run: bun tsc

      - name: knip
        run: bun knip
