name: Check

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read # for checkout
  actions: read # for actions-timeline

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: actions-timeline
        # cspell:ignore kesin
        uses: Kesin11/actions-timeline@1c2ab3f28225878ae4dd1f76d31279f16ea29e29 # v2.1.1

      - name: Checkout
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@8f24390df009a496891208e5e36b8a1de1f45135 # v1.2.1

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      - name: "commitlint (push: initial commit)"
        id: commitlint-push-initial
        # commit hash will be 0000000000000000000000000000000000000000 if it doesn't exist
        if: github.event_name == 'push' && github.event.before == '0000000000000000000000000000000000000000'
        run: bun run commitlint --verbose --to ${{github.event.after}}

      - name: commitlint (push)
        if: github.event_name == 'push' && steps.commitlint-push-initial.outcome == 'skipped'
        run: bun run commitlint --verbose --from ${{github.event.before}} --to ${{github.event.after}}

      - name: commitlint (pull_request)
        if: github.event_name == 'pull_request'
        run: |
          bun run commitlint --verbose --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }}

      - name: Biome
        run: bun run biome ci --error-on-warnings .

      - name: cspell
        run: bun run cspell "**/*"

      - name: tsc
        run: bun run tsc

      - name: knip
        run: bun run knip
